name: Docker Hub Deployment Cleanup
author: Ashen Gunaratne <mail@ashenm.ml>
description: Deletes obsolete Docker Hub deployments

inputs:
  repository:
    description: Docker Hub image repository
  excludes:
    description: Docker Hub image exclusion tags
    default: latest
  github_token:
    description: GitHub OAuth token
    required: true

runs:
  using: node12
  main: index.js
